# Change these first
owner: keithemyers # Your GitHub organization or username, where this repository lives
repo: tfaUptime # The name of this repository

sites:
  
  - name: Canvas
    url: https://thefirstacademy.instructure.com/
  - name: ClassLink LaunchPad
    url: https://launchpad.classlink.com/thefirstacademy
  - name: DyKnow
    url: https://dyknow.me/tfa
  - name: FACTS
    url: https://renweb1.renweb.com/renweb1/#/Home
  - name: FMX
    url: https://tfa.gofmx.com/login
  - name: Google Classroom
    url: https://classroom.google.com
  - name: Jamf Pro Cloud
    url: $JAMF_CLOUD_URL
  - name: Jamf Protect
    url: $JP_URL
  - name: uniFLOW Printing
    url: https://status.uniflowonline.com/

  
 

  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.thefirstacademy.org
  # baseUrl: /tfaUptime
  logoUrl: https://www.k12academics.com/sites/default/files/TFA-Logo-Horiz-wTagline%20(1).png
  name: System Status
  introTitle: "This system provides 24x7x365 monitoring of key TFA services. Any outages are reported via Slack and email alerts."
  introMessage: Managed by [i-Tech Support Inc.](https://www.i-techsupport.com/educational-tech/)
  navbar:
    - title: Upptime
      href: https://keithemyers.github.io/tfaUptime
    - title: Open a Support Ticket
      href: https://tfa.gofmx.com/

i18n:
  footer: 20240328/km


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
